-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT  CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    WHERE (DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10')
                    GROUP BY CAR_ID
                    HAVING COUNT(CAR_ID) >=5)
    AND (DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10')
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC


-- SELECT MONTH(HISTORY.START_DATE) AS MONTH, HISTORY.CAR_ID, COUNT(*) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
-- INNER JOIN ( SELECT CAR_ID, COUNT(*) AS CNT FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--                 WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10 GROUP BY CAR_ID) SUB_HISTORY
-- ON HISTORY.CAR_ID = SUB_HISTORY.CAR_ID WHERE SUB_HISTORY.CNT >= 5 AND YEAR(HISTORY.START_DATE) = 2022 AND MONTH(HISTORY.START_DATE) >= 8 AND MONTH(HISTORY.START_DATE) <= 10
-- GROUP BY HISTORY.CAR_ID, MONTH(HISTORY.START_DATE)
-- ORDER BY MONTH(HISTORY.START_DATE) ASC, HISTORY.CAR_ID DESC