-- 그룹별 조건에 맞는 식당 목록 출력하기

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE FROM MEMBER_PROFILE A
    JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
    WHERE A.MEMBER_NAME IN (
        SELECT MEMBER_NAME FROM (
            SELECT C.MEMBER_NAME, COUNT(REVIEW_ID) FROM MEMBER_PROFILE C
                JOIN REST_REVIEW D ON C.MEMBER_ID = D.MEMBER_ID
            GROUP BY MEMBER_NAME
        ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1) E
    )
ORDER BY REVIEW_DATE, REVIEW_TEXT