-- 주문량이 많은 아이스크림들 조회하기

SELECT FLAVOR FROM FIRST_HALF
WHERE FLAVOR IN (
    SELECT FLAVOR FROM (
        SELECT C.FLAVOR,(SUM(C.TOTAL_ORDER)) + D.TOTAL_ORDER FROM JULY C
        JOIN FIRST_HALF D ON C.FLAVOR = D.FLAVOR
        GROUP BY C.FLAVOR
        ORDER BY 2 DESC LIMIT 3
    )E 
)