-- 5월 식품들의 총매출 조회하기

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE*SUM(B.AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT A
JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE IN (
    SELECT PRODUCE_DATE FROM FOOD_ORDER
        WHERE PRODUCE_DATE LIKE "2022-05%" GROUP BY PRODUCT_ID)
GROUP BY B.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC
