-- 과일로 만든 아이스크림 고르기

SELECT F.FLAVOR FROM FIRST_HALF AS F
LEFT OUTER JOIN ICECREAM_INFO AS I
ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER >3000
    AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC